### ISSUE TITLE
Super-complaints - how to treat?

### ISSUE THREAD

**Issue by rgarner** [rgarner/cma-tna-crawlers#14]
Not sure if they're cases in the traditional sense? Do we need them? If so, where do they live, markets, consumer enforcement?

@adammaddison?

**Comment by adammaddison** [comment]
Christ.  Missed this one.  Sorry.  Will be included in email to Ruth.

**Comment by rgarner** [comment]
Closing - they're not showing up in sheets, so we're not interested.
