### ISSUE TITLE
Create body generator for old-style Mergers cases and Markets

### ISSUE THREAD

**Issue by rgarner** [rgarner/cma-tna-crawlers#18]
All markets and many old mergers cases need a body generator.

2002-2009 mergers cases were HTML- (not PDF-) based. While we collect that HTML, we don't do anything with it yet. We need to come up with a strategy to populate the body of the single document that each case will become, similar to [what we did for CC](https://github.com/rgarner/cma-tna-crawlers/blob/master/lib/cma/cc/body_generator.rb#L14-L46) previously.

Is it ok to note the order of the links in the case page, then generate a single body with appropriate headers for them later ([example](http://webarchive.nationalarchives.gov.uk/20140402141250/http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2008/coop-somerfield))? Should that order be most recent first, or as it was in the old site, in chronological order?

**Comment by rgarner** [comment]
Probably this can be made to fill in the other half of #17 at the same time; we don't know until the mergers crawler has finished whether or not we have ambiguous possible titles.

**Comment by adammaddison** [comment]
You say you did this for CC previously. Assume you mean for the open CC cases brought across in March '14? Don't suppose it's easy to point to an example open CC case you scraped?

**Comment by rgarner** [comment]
Sorry @adammaddison, @davidmann, overlooked your question.

Yes, here's a mergers case, [Anglo-American Lafarge](https://www.gov.uk/cma-cases/anglo-american-plc-lafarge-s-a-merger-inquiry) that was consolidated from several URLs starting [here](http://webarchive.nationalarchives.gov.uk/20140402141250/http://www.competition-commission.org.uk/our-work/directory-of-all-inquiries/anglo-american-lafarge).  The left hand menu was crawled, and the constituent parts reassembled in an [order requested by CMA](https://github.com/rgarner/cma-tna-crawlers/blob/master/lib/cma/cc/body_generator.rb#L14-L46).

In this case, I am currently reassembling these links in the order that they were encountered on the page. There are typically fewer (read: 1) sections, so this is an edge case for 25 cases in mergers:

http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2003/sibelco
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2003/stena
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2004/firstgroup2
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2005/britannic
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2005/national
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2005/william-hill
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2006/aggregate
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2006/boots
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2006/coop2
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2007/Co-op
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2007/Flybe
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2007/Inchcape
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2007/lloyds
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2007/Tesco
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2008/AirFrance
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2008/coop-somerfield
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2008/Diageo
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2008/Dunfermline
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2008/globalradio
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2008/Home
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2008/SRCL-Cliniserve
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2009/Aggregate
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2009/Co-operative2
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2009/cooperative2
http://www.oft.gov.uk/OFTwork/mergers/Mergers_Cases/2009/sports-direct-inter

and similarly low cardinality for markets:

http://www.oft.gov.uk/OFTwork/markets-work/references/aggregates-MIR
http://www.oft.gov.uk/OFTwork/markets-work/references/airports
http://www.oft.gov.uk/OFTwork/markets-work/references/bus-services
http://www.oft.gov.uk/OFTwork/markets-work/references/classified-directory
http://www.oft.gov.uk/OFTwork/markets-work/references/extended-warranties
http://www.oft.gov.uk/OFTwork/markets-work/references/payment
http://www.oft.gov.uk/OFTwork/markets-work/references/store-cards1
